version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run eslint
      - run: npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test